apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-k8s
  template:
    metadata:
      labels:
        app: poc-k8s
    spec:
      containers:
      - name: goserver
        image: ca1o19c/poc-k8s:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
